cloudprem/eks.tf

Our site cloning feature relies upon the S3 API calls `ListObjectsV2` and `CopyObject` so we need those actions. In order to use `ListObjectsV2` we also need `ListBucket` so that has been added as well.

Update S3 policy for the EKS workers

---

cloudprem/kubernetes.tf

Our app code can consume a `/etc/dozuki/sentry.json` file to add a list of tags when sending exceptions to Sentry. This adds the `deployment` tag.

Add the Sentry configuration file

---

cloudprem/kubernetes.tf

Background
--
This configuration is used to determine how to connect to the memcached server that's used to acquire mutexes for nanosites when running integration tests. This may not get us all the way to being able to run all integration tests in CloudPrem, but it will at least get us one step closer.
QA
--
I'm not sure how QA is being done on CloudPrem these days, but this should have no effect on the application's regular behavior.
CC @scbarber @ddvdozuki

Add memcached test cluster configs

---

.github/workflows/release.yml

This is the changelog for v2.0. I opted for a major version increment as it's consistent with the semver standard. Nothing from v1.x is compatible with the current code so a major version bump is warranted.
Once this PR is approved and merged I will create and push the tag to create the release in GitHub.

Release v2.0 of Terraform CloudPrem Infra

---

cloudprem/physical/README.md
cloudprem/physical/main.tf
cloudprem/physical/rds.tf

This is a minor change to our parameter groups to add `group_concat_max_len` parameter to better match with our production cloud configuration. The lack of it was causing an issue with our customers data when migrating from production cloud as we use Persona in production and vanilla MySQL in private cloud. 
Fixes https://github.com/iFixit/dozuki/issues/3108

RDS Parameter Fix

---

cloudprem/logical/kubernetes.tf

The `index.json` file was removed as a configuration dependency in newer versions of the application so we stopped creating it with the infra code but to support older versions of the app, especially during migrations, we need this file to exist. 

Restore index.json app config file to maintain backwards compatibility

---

.github/workflows/terraform.yml
cloudprem/physical/static/bastion_userdata.yml

The `kubectl` utility had an update that made it incompatible with the current available versions of EKS which ended up breaking our bastion's ability to access customer EKS instances. This change locks the `kubectl` version to a known good one instead of just always downloading the latest version.
Additionally I've done some fixing of the tfsec and reviewdog configuration in the GitHub action workflow to improve it's functionality and reliability.

Lock kubectl utility to known good version.

---

.github/workflows/terraform.yml
cloudprem/physical/README.md
cloudprem/physical/main.tf
cloudprem/physical/modules/vpn/acm_ca.tf
cloudprem/physical/modules/vpn/acm_server.tf
cloudprem/physical/modules/vpn/config.tf
cloudprem/physical/modules/vpn/endpoint.tf
cloudprem/physical/modules/vpn/logs.tf
cloudprem/physical/modules/vpn/main.tf
cloudprem/physical/modules/vpn/outputs.tf
cloudprem/physical/modules/vpn/s3.tf
cloudprem/physical/modules/vpn/sg.tf
cloudprem/physical/modules/vpn/variables.tf
cloudprem/physical/nlb.tf
cloudprem/physical/outputs.tf
cloudprem/physical/rds.tf
cloudprem/physical/s3.tf
cloudprem/physical/static/bastion_userdata.yml
cloudprem/physical/util/dms-stop.sh
cloudprem/physical/variables.tf
cloudprem/physical/vpc.tf
live/gov/us-gov-west-1/bi/env.hcl
live/standard/eu-central-1/bi/env.hcl
live/standard/eu-west-1/bi/env.hcl
live/standard/eu-west-2/bi/env.hcl
live/standard/eu-west-3/bi/env.hcl
live/standard/us-east-1/bi/env.hcl
live/standard/us-east-2/bi/env.hcl
live/standard/us-west-2/bi/env.hcl

Customers will likely need access to their BI database from outside the AWS network. Our existing configuration relies on their account having an existing transit gateway managed outside the terraform. 
We will now conditionally provision a VPN endpoint to the VPC which will allow access to authenticated users. The VPN configuration is such that only the BI database will be accessible from within the VPN and the user may configure which CIDRs they want to allow to connect to the VPN. Our VPN uses mutual authentication which relies on 2048 bit RSA self-signed TLS certificates. We generate and upload the certificates embedded in an OpenVPN configuration file to a secure S3 bucket for distribution. The bucket name and BI Database secret containing the connection information is output after …

BI Database VPN Access & VPN Module

---

.github/workflows/terraform.yml
cloudprem/compute/README.md
cloudprem/compute/main.tf
cloudprem/storage/README.md
cloudprem/storage/main.tf
cloudprem/storage/outputs.tf
cloudprem/storage/rds.tf
cloudprem/storage/variables.tf

This adds public BI functionality to the legacy 4 module infra. I also added the `group_concat_max_len` parameter that was missing to the parameter group config and the terraform provider version constraints to fix the helm provider v1alpha1 authentication api bug.

Legacy Public BI Access

---

.github/workflows/release.yml

We're making this release because some customers are on our legacy module configuration that is not upgradeable to our current incarnation without a full migration and they need these upgrades.
In the future we will need to figure out a viable upgrade strategy for them.

Release 2.0.1 legacy module backport fixes

---

cloudprem/physical/nlb.tf
cloudprem/physical/variables.tf
live/tests/common/config.go

Due to an oversight we were only allowing a single CIDR to access the dashboard and the app, now we allow a list of CIDRs for each.

Allow multiple ingress CIDRs for app and dashboard

---

cloudprem/logical/README.md
cloudprem/logical/main.tf
cloudprem/physical/bastion.tf
cloudprem/physical/main.tf
cloudprem/physical/rds.tf
cloudprem/physical/s3.tf

We had some changes to the terraform that was breaking backwards compatibility and causing terraform to try to delete and re-create resources erroneously. This fixes that by using `moved` blocks to tell terraform which resources we renamed as well as lifecycle rules to ignore changes where appropriate.

Fix upgrading from older versions (<=2.5.4)

---

cloudprem/logical/README.md
cloudprem/logical/kubernetes.tf
cloudprem/logical/main.tf
cloudprem/logical/static/frontegg-db.sql
cloudprem/logical/static/sites-db.sql
cloudprem/logical/webhooks.tf
cloudprem/physical/eks.tf

Creating the frontegg database AND updating the sites db to enable webhooks in the same k8 job makes the entire process very fragile and susceptible to order of operations issues. This splits those and does them when more appropriate. The frontegg db is created as soon as we have a database connection whereas the sites db update waits for the app to be ready (and therefore the sites db actually existing) before trying to update it.

Webhooks DB Update Fix

---

cloudprem/common/acm/ca.tf
cloudprem/common/acm/cert.tf
cloudprem/common/acm/main.tf
cloudprem/common/acm/outputs.tf
cloudprem/common/acm/variables.tf
cloudprem/logical/README.md
cloudprem/logical/bi.tf
cloudprem/logical/main.tf
cloudprem/logical/static/grafana_values.yml
cloudprem/logical/variables.tf
cloudprem/physical/README.md
cloudprem/physical/main.tf
cloudprem/physical/modules/vpn/config.tf
cloudprem/physical/modules/vpn/endpoint.tf
cloudprem/physical/modules/vpn/main.tf
cloudprem/physical/modules/vpn/variables.tf

My MVP of Grafana did not include SSL access for the frontend, this PR adds that by using the self-signed cert functionality of the VPN module. I refactored said functionality into its own module, now stored in the `common` root directory, and is used by _both_ the VPN module _and_ the Grafana implementation. Additionally I refactored the way I set Grafana config directives: I no longer use the `grafana.ini` option in the helm chart, opting instead for environment variables set via a k8 secret.

Add SSL to Grafana frontend

---

cloudprem/physical/main.tf

Just came across a bug when BI is set to public and a whitelist is used. It effectively blocks the app cluster from communicating with the BI database which is required by Grafana. This change ensures everything in the private VPC can access the replicate database.

Ensure BI access when restricted whitelisting is in place

---

.github/workflows/terraform.yml
live/common.hcl
terraform/bootstrap/main.tf
terraform/logical/README.md
terraform/logical/main.tf
terraform/logical/outputs.tf
terraform/logical/replicated.tf
terraform/logical/variables.tf
terraform/physical/README.md
terraform/physical/bastion.tf
terraform/physical/eks.tf
terraform/physical/main.tf
terraform/physical/modules/acm/ca.tf
terraform/physical/modules/acm/cert.tf
terraform/physical/modules/acm/main.tf
terraform/physical/modules/vpn/config.tf
terraform/physical/modules/vpn/endpoint.tf
terraform/physical/modules/vpn/main.tf
terraform/physical/modules/vpn/s3.tf
terraform/physical/monitoring.tf
terraform/physical/nlb.tf
terraform/physical/outputs.tf
terraform/physical/rds.tf
terraform/physical/s3.tf
terraform/physical/termination.tf
terraform/physical/util/create-s3-batch.sh
terraform/physical/variables.tf
terraform/physical/vpc.tf

Our migration system had a fundamental flaw. We could take an existing RDS snapshot and existing S3 buckets to launch a new instance, however that old instance still has a terraform state entry for those S3 buckets. What happens when that old unneeded instance is torn down? The answer is the customer data goes away. 
The easiest solution is to simply perform state surgery on that old instance and remove the references to those buckets before deleting and while that works it's far from ideal. One forgotten move or misstep and all of our customer's data is gone forever. I believe this potential calamity is reason enough to invest in a safer replication strategy.
We now create new buckets for each environment regardless of migration state. If migrating, we will setup replication rules on the …

Intelligent S3 bucket migration support

---

terraform/physical/s3.tf

This came up while updating one of our customers from a very old version of the infra to the latest v3.2. In the time between the releases we changed our bucket naming scheme and this triggers a re-create by default for s3 bucket resources. 
I've added lifecycle ignore blocks to the relevant resources to prevent recreation when the bucket name or prefix changes.

Fix S3 bucket re-create when name or prefix changes during upgrade

---

terraform/physical/README.md
terraform/physical/s3.tf

The default KMS policy does not allow for replication. These changes add the necessary policy to allow for batch replication jobs as well as bucket replication rules.

Fix S3 KMS Key Policy

---

live/Dockerfile
live/generate_live_env.sh
live/isolated_run.sh
live/terragrunt.hcl

This is a shell script and small Dockerfile to allow developers to run multiple iterations of the terraform on their workstations without being tied to the source material. This is helpful when testing changes and upgrades to old versions.
The previous workflow for testing changes looked like:
1. Stash working changeset
2. Check out previous tag or master
3. Trigger deploy of checked out version
4. wait.......... coffee....
5. Once completed we then check out the working branch
6. apply the stash of our working changes
7. Trigger deploy of new version on top of the old version to test upgrading.
8. wait........ coffee.....
9. profit?
All the while during those wait periods you were unable to make any changes to the terraform or live environment due to the multi root module configuration …

Isolated Run Script for Live Environment

---

terraform/logical/replicated.tf

In the course of incorporating the feature to update the KOTS configuration each time the terraform reruns the logical module, I mistakenly caused the entire configuration to be overwritten. This error stemmed from an assumption that the default behavior would be a "merge", but this turned out to be incorrect. To rectify this, it is necessary to explicitly use the --merge tag. Doing so will prevent the function from inadvertently erasing any customized settings made from the dashboard.

Correction to KOTS Configuration Update: Preventing Overwrites with --merge Tag

---

terraform/physical/bi.tf
terraform/physical/static/dms_mapping.json

In our ongoing efforts to minimize the failure rate of DMS, we have implemented several alterations to our conditional replication setup and our approach to establishing and connecting to the replica database. Most importantly, we now completely turn off multi-az for the target replica, aligning with AWS' best-practice recommendation. Likewise, we have disabled foreign key checks in the target database to further enhance performance and reliability.
The most significant shift, however, is in our strategy for schema mapping. Rather than solely relying on an exclusive blacklist, we've transitioned to a dual-pronged approach that incorporates both a whitelist and a blacklist as needed. This shift aims to better manage and mitigate any potential errors by excluding databases and tables that …

Enhancing DMS Performance: Updates to Replication Setup and Schema Mapping Strategy
