- .github/workflows/release.yml
- cloudprem/static/userdata.yml
I somehow messed up the formatting on the user data embedded script which broke the user data entirely so there's no way to debug current cloudprem installations so this is classified as a hot fix.
> Bastion userdata fix

- .github/workflows/release.yml
- .github/workflows/terraform.yml
- cloudprem/logical/README.md
- cloudprem/logical/main.tf
- cloudprem/logical/variables.tf
- cloudprem/physical/README.md
- cloudprem/physical/nlb.tf
This is the changelog for v2.5. I opted for a major version increment as it's consistent with the semver standard. Nothing from v2.0 is compatible with the current code so a major version bump is warranted.
Once this PR is approved and merged I will create and push the tag to create the release in GitHub.
> Releasing v2.5

- .github/workflows/release.yml
Changelog update to reflect minor v2.5.1 changes.
> Releasing v2.5.1

- .github/workflows/release.yml
> Update release workflow to reflect changes in 2.5.2

- .github/workflows/release.yml
> Releasing v2.5.3

- .github/workflows/release.yml
> Releasing v2.5.4

- .github/workflows/release.yml
> Releasing v2.6

- .github/workflows/release.yml
> Release 2.6.1

- .github/workflows/release.yml
> Releasing v2.7

- .github/workflows/release.yml
> Releasing v2.7.1

- .github/workflows/release.yml
> Releasing v2.7.2

- .github/workflows/release.yml
> Releasing v2.7.3

- .github/workflows/release.yml
> Releasing v2.7.4

- .github/workflows/release.yml
> Releasing v2.7.5

- .github/workflows/release.yml
> Releasing v2.7.6

- cloudprem/physical/variables.tf
> Fix identifier validation to re-allow empty values

- .github/workflows/release.yml
> Releasing v2.7.7

- cloudprem/logical/kubernetes.tf
This is needed to configure the app to use the SSL cert to sign SAML requests.
> Add the saml.json config

- cloudprem/logical/charts/kubed/Chart.yaml
- cloudprem/logical/charts/kubed/OWNERS
- cloudprem/logical/charts/kubed/README.md
- cloudprem/logical/charts/kubed/doc.yaml
- cloudprem/logical/charts/kubed/templates/NOTES.txt
- cloudprem/logical/charts/kubed/templates/_helpers.tpl
- cloudprem/logical/charts/kubed/templates/apiregistration.yaml
- cloudprem/logical/charts/kubed/templates/cluster-role-binding.yaml
- cloudprem/logical/charts/kubed/templates/cluster-role.yaml
- cloudprem/logical/charts/kubed/templates/deployment.yaml
- cloudprem/logical/charts/kubed/templates/secret.yaml
- cloudprem/logical/charts/kubed/templates/service.yaml
- cloudprem/logical/charts/kubed/templates/serviceaccount.yaml
- cloudprem/logical/charts/kubed/values.yaml
- cloudprem/logical/kubernetes.tf
> Update kubed config syncer chart to latest version

- .github/workflows/release.yml
> Releasing v2.7.9

- .github/workflows/release.yml
Release notes for KOTS deployment major update.
> Release v3.0
